import { CompanyInfo, Destination, TravelService, CuratedPackage } from "./types";

export const companyData: CompanyInfo = {
  name: "SMALL DADDY PLUS",
  tagline: "Your Journey, Our Responsibility",
  founder: "Priykant Gupta",
  experienceYears: "15+",
  satisfiedCustomers: "25,000+",
  formerName: "Ranjan Services",
  address: "6/B, Jagdish Chamber, Opp. Rajkamal Petrol pump, Highway, Mehsana 384002 - Gujarat",
  phones: ["+91 94272 86755", "+91 91731 36111"],
  whatsapp: "919427286755",
  emails: ["info@rtravelworld.com", "rtravelworldmehsana@gmail.com"],
};

export const goaCarouselSlides = [
  {
    id: "goa-1",
    title: "Golden Beaches & Sunset Waves",
    subtitle: "Experience the sun-kissed shores of Palolem, Baga & Calangute with private beachfront stays.",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1600&auto=format&fit=crop",
    badge: "Exclusive 4N/5D Goa Coastal Bliss",
    tag: "Trending Destination",
    price: "From ₹12,999 / person",
  },
  {
    id: "goa-2",
    title: "Heritage Forts & Portuguese Villas",
    subtitle: "Wander through colorful Latin quarters of Fontainhas, historic Aguada & Chapora Forts.",
    image: "https://images.unsplash.com/photo-1587922546307-776227941871?q=80&w=1600&auto=format&fit=crop",
    badge: "Cultural & Heritage Tours",
    tag: "Historical Marvels",
    price: "From ₹14,499 / person",
  },
  {
    id: "goa-3",
    title: "Luxury Catamaran & Island Cruises",
    subtitle: "Sail along the pristine Mandovi river, spot dolphins at Grand Island, and enjoy watersports.",
    image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=1600&auto=format&fit=crop",
    badge: "VIP Yacht & Watersport Experience",
    tag: "Adventure & Thrill",
    price: "From ₹16,999 / person",
  },
  {
    id: "goa-4",
    title: "Tropical Palms & Serene Backwaters",
    subtitle: "Unwind at tranquil South Goa resorts surrounded by emerald palms and serene coastal rivers.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600&auto=format&fit=crop",
    badge: "Custom Family & Honeymoon Retreat",
    tag: "Ultimate Relaxation",
    price: "From ₹18,500 / person",
  },
];

export const destinationsData: Destination[] = [
  {
    id: "gujarat",
    name: "Gujarat",
    tagline: "Land of Legends",
    category: "india",
    image: "https://images.unsplash.com/photo-1609137144813-7d9921338f24?q=80&w=800&auto=format&fit=crop",
    duration: "5 Days / 4 Nights",
    startingPrice: "₹14,999",
    featured: true,
    highlights: ["Rann of Kutch", "Statue of Unity", "Somnath & Dwarka Temple", "Gir National Park"],
  },
  {
    id: "kashmir",
    name: "Kashmir",
    tagline: "Paradise on Earth",
    category: "india",
    image: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹19,499",
    featured: true,
    highlights: ["Dal Lake Shikara", "Gulmarg Gondola", "Pahalgam Valley", "Sonamarg Glaciers"],
  },
  {
    id: "himachal",
    name: "Himachal Pradesh",
    tagline: "Snowy Peaks & Alpine Wonder",
    category: "india",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹16,999",
    featured: true,
    highlights: ["Manali & Rohtang Pass", "Shimla Ridge", "Solang Valley", "Kasol & Spiti"],
  },
  {
    id: "uttarakhand",
    name: "Uttarakhand",
    tagline: "Devbhoomi Valley & Serenity",
    category: "india",
    image: "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?q=80&w=800&auto=format&fit=crop",
    duration: "7 Days / 6 Nights",
    startingPrice: "₹18,500",
    featured: true,
    highlights: ["Rishikesh River Rafting", "Mussoorie Hills", "Nainital Lake", "Char Dham Yatra"],
  },
  {
    id: "goa",
    name: "Goa",
    tagline: "Sun, Sea & Golden Beaches",
    category: "india",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=800&auto=format&fit=crop",
    duration: "4 Days / 3 Nights",
    startingPrice: "₹12,999",
    featured: true,
    highlights: ["Baga Beach Nightlife", "Dudhsagar Waterfalls", "Scuba & Watersports", "Private Yacht Cruises"],
  },
  {
    id: "kerala",
    name: "Kerala",
    tagline: "God's Own Country",
    category: "india",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹17,999",
    featured: true,
    highlights: ["Alleppey Houseboat", "Munnar Tea Gardens", "Thekkady Wildlife", "Kovalam Beach"],
  },
  {
    id: "maharashtra",
    name: "Maharashtra",
    tagline: "Heritage & Mist-Covered Hills",
    category: "india",
    image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?q=80&w=800&auto=format&fit=crop",
    duration: "4 Days / 3 Nights",
    startingPrice: "₹11,999",
    featured: false,
    highlights: ["Mahabaleshwar & Lonavala", "Ajanta & Ellora Caves", "Alibaug Coast", "Shirdi Darshan"],
  },
  {
    id: "tamil-nadu",
    name: "Tamil Nadu",
    tagline: "Land of Ancient Temples",
    category: "india",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=800&auto=format&fit=crop",
    duration: "5 Days / 4 Nights",
    startingPrice: "₹15,499",
    featured: false,
    highlights: ["Madurai Meenakshi", "Rameshwaram Corridor", "Ooty Toy Train", "Kanyakumari Sunset"],
  },
  {
    id: "odisha",
    name: "Odisha",
    tagline: "Art, Heritage & Temples",
    category: "india",
    image: "https://images.unsplash.com/photo-1620619767323-b95a89183081?q=80&w=800&auto=format&fit=crop",
    duration: "5 Days / 4 Nights",
    startingPrice: "On Request",
    featured: false,
    highlights: ["Puri Jagannath Temple", "Konark Sun Temple", "Chilika Lake Dolphins", "Bhubaneswar Heritage"],
  },
  {
    id: "sikkim",
    name: "Sikkim",
    tagline: "Himalayan Beauty & Monasteries",
    category: "india",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹21,999",
    featured: true,
    highlights: ["Tsomgo Lake", "Nathula Pass", "Gangtok Cable Car", "Yumthang Flower Valley"],
  },
  {
    id: "darjeeling",
    name: "Darjeeling",
    tagline: "Queen of the Hills",
    category: "india",
    image: "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?q=80&w=800&auto=format&fit=crop",
    duration: "4 Days / 3 Nights",
    startingPrice: "₹14,500",
    featured: false,
    highlights: ["Tiger Hill Sunrise", "Batasia Loop", "Toy Train Joy Ride", "Happy Valley Tea Estate"],
  },
  {
    id: "meghalaya",
    name: "Meghalaya",
    tagline: "Abode of Clouds & Living Roots",
    category: "india",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=800&auto=format&fit=crop",
    duration: "5 Days / 4 Nights",
    startingPrice: "₹19,999",
    featured: false,
    highlights: ["Cherrapunji Waterfalls", "Dawki Crystal River", "Living Root Bridges", "Mawlynnong Village"],
  },
  {
    id: "andaman",
    name: "Andaman & Nicobar",
    tagline: "Tropical Island Paradise",
    category: "india",
    image: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹24,999",
    featured: true,
    highlights: ["Radhanagar Beach Havelock", "Scuba & Coral Snorkeling", "Cellular Jail Light Show", "Neil Island"],
  },
  {
    id: "ladakh",
    name: "Leh Ladakh",
    tagline: "High Mountain Passes & Pangong Tso",
    category: "india",
    image: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?q=80&w=800&auto=format&fit=crop",
    duration: "7 Days / 6 Nights",
    startingPrice: "₹26,999",
    featured: true,
    highlights: ["Pangong Tso Blue Lake", "Khardung La World's Highest Pass", "Nubra Valley Sand Dunes", "Magnetic Hill"],
  },
  // International Destinations
  {
    id: "dubai",
    name: "Dubai, UAE",
    tagline: "Futuristic Wonder & Desert Safaris",
    category: "international",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=800&auto=format&fit=crop",
    duration: "5 Days / 4 Nights",
    startingPrice: "₹45,999",
    featured: true,
    highlights: ["Burj Khalifa Top Floor", "Desert Dune Bashing & BBQ", "Marina Dhow Cruise", "Museum of the Future"],
  },
  {
    id: "bali",
    name: "Bali, Indonesia",
    tagline: "Island of Gods & Tropical Luxury",
    category: "international",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹42,500",
    featured: true,
    highlights: ["Ubud Rice Terraces", "Tanah Lot Sea Temple", "Nusa Penida Kelingking", "Private Pool Villa Stay"],
  },
  {
    id: "maldives",
    name: "Maldives",
    tagline: "Overwater Villas & Turquoise Lagoons",
    category: "international",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=800&auto=format&fit=crop",
    duration: "4 Days / 3 Nights",
    startingPrice: "₹59,999",
    featured: true,
    highlights: ["Luxury Water Villa Stay", "Manta Ray Snorkeling", "Sunset Speedboat Cruise", "Candlelight Beach Dinner"],
  },
  {
    id: "thailand",
    name: "Thailand (Phuket & Krabi)",
    tagline: "Emerald Bays & Vibrant Culture",
    category: "international",
    image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹34,999",
    featured: true,
    highlights: ["Phi Phi Island Speedboat", "James Bond Island", "Bangkok Grand Palace", "Coral Reef Snorkeling"],
  },
  {
    id: "singapore",
    name: "Singapore",
    tagline: "Garden City & Universal Studios",
    category: "international",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=800&auto=format&fit=crop",
    duration: "5 Days / 4 Nights",
    startingPrice: "₹52,000",
    featured: false,
    highlights: ["Marina Bay Sands SkyPark", "Gardens by the Bay", "Sentosa Island", "Night Safari"],
  },
  {
    id: "switzerland",
    name: "Switzerland",
    tagline: "Alpine Enchantment & Scenic Trains",
    category: "international",
    image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=800&auto=format&fit=crop",
    duration: "7 Days / 6 Nights",
    startingPrice: "₹1,25,000",
    featured: true,
    highlights: ["Jungfraujoch Top of Europe", "Mount Titlis Cable Car", "Lake Lucerne Cruise", "Interlaken Valley"],
  },
];

export const servicesData: TravelService[] = [
  {
    id: "flight-booking",
    title: "Flight Booking",
    shortDesc: "Domestic & International airfares with exclusive agent fares and instant confirmation.",
    fullDesc: "Best rates for domestic and international carriers, special student & corporate baggage allowances, seat selection, and 24/7 web check-in assistance.",
    iconName: "Plane",
    badge: "Special Airfares",
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "railway-reservation",
    title: "Railway Reservation",
    shortDesc: "Hassle-free IRCTC confirmed bookings, Tatkal support & tourist train planning.",
    fullDesc: "Complete railway ticketing assistance across all classes (1AC, 2AC, 3AC, Vande Bharat, Tejas Express) with route guidance and meal selections.",
    iconName: "Train",
    badge: "Tatkal & Vande Bharat",
    image: "https://images.unsplash.com/photo-1532105956626-9569c03602f6?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "group-tours",
    title: "Group Tours",
    shortDesc: "Curated community & family group departures with dedicated tour managers.",
    fullDesc: "Stress-free group travel with inclusive meals, luxury AC coach transfers, Gujarati/Jain food arrangements, and expert local guides.",
    iconName: "Users",
    badge: "Guided Group Departures",
    image: "https://images.unsplash.com/photo-1539635278303-d4002c07eae3?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "corporate-tours",
    title: "Corporate Tours (MICE)",
    shortDesc: "Executive travel, annual retreats, dealer meets, and incentive conference trips.",
    fullDesc: "End-to-end MICE solutions including conference hall setups, team bonding adventures, airport meet & greets, and bulk billing.",
    iconName: "Briefcase",
    badge: "MICE & Business Travel",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "customized-holidays",
    title: "Customized Holidays",
    shortDesc: "Tailor-made itineraries designed exclusively to match your exact dates and budget.",
    fullDesc: "Choose your pace, select boutique stays, personalize daily sightseeing, and travel with your own private vehicle and chauffeur.",
    iconName: "Compass",
    badge: "100% Tailored Itinerary",
    image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "domestic-tour-packages",
    title: "Domestic Tour Packages",
    shortDesc: "Comprehensive holiday packages covering the vibrant states of India.",
    fullDesc: "From Kashmir to Kanyakumari, and Gujarat to the North East, experience verified 3-star to 5-star hotels, safe transport, and curated sightseeing.",
    iconName: "MapPin",
    badge: "All-India Coverage",
    image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "family-holidays",
    title: "Family Holidays",
    shortDesc: "Safe, comfortable vacations packed with fun for children and leisure for elders.",
    fullDesc: "Kid-friendly resorts, spacious inter-connecting rooms, comfortable vehicle pacing, and memorable activities for every generation.",
    iconName: "HeartHandshake",
    badge: "All Generations Welcome",
    image: "https://images.unsplash.com/photo-1511895426328-dc8714191300?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "honeymoon-tours",
    title: "Honeymoon Tours",
    shortDesc: "Romantic getaways with candlelit dinners, flower beds, and private pool villas.",
    fullDesc: "Special inclusions like beachfront dinners, honeymoon cakes, couple spa sessions, and idyllic destinations like Maldives, Bali, Kashmir & Kerala.",
    iconName: "Sparkles",
    badge: "Romantic Specials",
    image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "pilgrimage-tours",
    title: "Pilgrimage Tours",
    shortDesc: "Spiritual journeys to holy shrines with senior citizen care and darshan arrangements.",
    fullDesc: "Specialized tours for Char Dham, Vaishno Devi, Somnath-Dwarka, Jyotirlinga Darshan, Tirupati, Shirdi, and Ayodhya with dedicated assistance.",
    iconName: "Sun",
    badge: "Spiritual Yatra Care",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "hotel-booking",
    title: "Hotel Booking",
    shortDesc: "Handpicked premium hotels, heritage havelis, beachfront stays & luxury resorts.",
    fullDesc: "Verified quality, best negotiated corporate rates, complimentary breakfasts, early check-in assistance, and guaranteed room categories.",
    iconName: "Building2",
    badge: "Verified Stays",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "car-rental",
    title: "Car Rental",
    shortDesc: "Chauffeur-driven AC sedans, Innova Crysta, tempo travellers & luxury coaches.",
    fullDesc: "Reliable intercity transfers, airport pick & drop, local sightseeing cabs with courteous verified drivers and zero surge pricing.",
    iconName: "Car",
    badge: "Clean Fleet & Verified Drivers",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800&auto=format&fit=crop",
  },
];

export const curatedRegionsList = [
  "Gujarat",
  "Uttar Pradesh",
  "Uttarakhand",
  "Himachal",
  "Jammu Kashmir",
  "North East",
  "Bengal & Odisha",
  "Kerala",
  "Tamil Nadu",
  "Goa",
  "Maharashtra",
  "Karnataka",
];

export const initialCuratedPackages: CuratedPackage[] = [
  {
    id: "pkg-goa-1",
    state: "Goa",
    title: "Goa Coastal Paradise & Watersports Package",
    subtitle: "Scuba, Dolphin Safari & Island Cruise Special",
    route: "2N Calangute • 1N Baga Beach",
    duration: "4 Days & 3 Nights",
    categoryBadge: "Beach & Watersports",
    badgeGradient: "from-pink-500 to-rose-500",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=800&auto=format&fit=crop",
    originalPrice: "16,500",
    discountedPrice: "11,999",
    savings: "4,501",
    highlights: [
      "Grand Island Scuba & Snorkeling",
      "Dudhsagar Waterfall Jeep Safari",
      "North Goa Forts (Aguada & Chapora)",
      "Sunset Cruise on Mandovi River",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival in Goa & North Beach Stroll",
        description: "Private cab pickup from Mopa / Dabolim Airport or Thivim Railway Station. Check-in to your Calangute beachfront resort. Evening stroll along Calangute and Baga beaches with lively beach shacks and sunset views.",
      },
      {
        day: 2,
        title: "Grand Island Boat Cruise, Dolphin Safari & Scuba",
        description: "Early morning boat transfer to Grand Island. Enjoy dolphin spotting in Arabian waters, guided scuba diving with professional equipment & underwater photos, followed by swimming and a delicious Goan buffet lunch on the island.",
      },
      {
        day: 3,
        title: "North Goa Sightseeing & Sunset River Cruise",
        description: "Explore Aguada Fort and lighthouse, Chapora Fort (Dil Chahta Hai point), Anjuna & Vagator beaches. In the evening, enjoy a 1-hour luxury catamaran cruise on the Mandovi River with live DJ and folk dance performances.",
      },
      {
        day: 4,
        title: "Local Shopping & Departure Transfer",
        description: "Breakfast at the resort. Free time for souvenir shopping at Panaji Market or Calangute Mall. Timely private transfer to the airport or railway station for your onward journey.",
      },
    ],
    inclusions: [
      "3 Nights AC Deluxe Stay in Calangute / Baga",
      "Daily Buffet Breakfast",
      "Grand Island Boat Cruise with Scuba Diving Gear",
      "Mandovi River Sunset Cruise Tickets",
      "Private AC Cab for all Sightseeing & Transfers",
      "24/7 Dedicated Trip Manager Support",
    ],
    detailedInclusions: [
      {
        id: "inc-1",
        title: "Grand Island Scuba Diving & Dolphin Safari Cruise",
        description: "Set sail on a morning catamaran cruise across the Arabian Sea. Watch wild dolphins jumping in their natural habitat, and plunge into vibrant coral reefs with certified PADI dive masters, complete with safety gear and underwater video/photos.",
        image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-2",
        title: "4-Star Beachside Deluxe Resort Stay with Swimming Pool",
        description: "Enjoy 3 nights of serene coastal living in handpicked 4-star beachside resorts in Calangute and Baga. Features air-conditioned rooms, private sun terrace, lush swimming pool, and lavish daily chef-curated morning buffet breakfast.",
        image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-3",
        title: "Private Dedicated AC Sedan / SUV for All Sightseeing",
        description: "Travel with complete peace of mind in an exclusive sanitized air-conditioned vehicle. Covers all airport or railway station pickups, drop-offs, intercity beach transfers, Aguada Fort, Chapora, and local shopping with zero surge pricing.",
        image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-4",
        title: "Sunset Catamaran River Cruise on Mandovi River",
        description: "Experience the magic of twilight from the deck of a luxury riverboat on Mandovi River. Includes live traditional Goan folk dances, DJ music sessions, complimentary beverages, and breathtaking sunset panoramas over the coastline.",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-5",
        title: "24/7 Dedicated On-Trip Concierge & Trip Manager Support",
        description: "Our dedicated Mehsana & Goa ground coordination team remains at your service throughout the tour. Enjoy seamless hotel check-ins, curated shack dining recommendations, watersport discounts, and 24/7 emergency care.",
        image: "",
      },
    ],
    exclusions: [
      "Airfare / Train tickets (Available on request at special discounted fares)",
      "Lunch and Dinners not specified in inclusions",
      "Personal watersport rides like parasailing & jet ski (available at discounted partner rates)",
    ],
    featured: true,
  },
  {
    id: "pkg-goa-2",
    state: "Goa",
    title: "South Goa Heritage & Luxury Retreat",
    subtitle: "Portuguese Latin Quarters & Luxury Backwaters",
    route: "2N Palolem • 2N Colva / Cavelossim",
    duration: "5 Days & 4 Nights",
    categoryBadge: "Heritage & Romance",
    badgeGradient: "from-indigo-500 to-purple-500",
    image: "https://images.unsplash.com/photo-1587922546307-776227941871?q=80&w=800&auto=format&fit=crop",
    originalPrice: "19,000",
    discountedPrice: "14,499",
    savings: "4,501",
    highlights: [
      "Fontainhas Latin Quarter Heritage Walk",
      "Private Mandovi River Sunset Catamaran",
      "Basilica of Bom Jesus & Se Cathedral",
      "Pristine Palolem & Agonda Beach Stays",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival & Transfer to South Goa Serenity",
        description: "Warm welcome at Goa airport/station and scenic transfer to South Goa resort in Colva. Spend the evening soaking in the calm sunset, coconut groves, and tranquil shoreline.",
      },
      {
        day: 2,
        title: "Old Goa Heritage Churches & Fontainhas",
        description: "Visit UNESCO World Heritage Sites: Basilica of Bom Jesus, Se Cathedral, and Church of St. Francis of Assisi. Guided walking tour through colorful Portuguese quarters of Fontainhas in Panaji.",
      },
      {
        day: 3,
        title: "Spice Plantation Tour & Mandovi Cruise",
        description: "Guided tour through an authentic organic Goan spice plantation with traditional lunch on banana leaves. Sunset river cruise with Goan cultural troupe performance.",
      },
      {
        day: 4,
        title: "Palolem Beach, Butterfly Island & Sunset Point",
        description: "Drive south to Palolem Beach. Experience a private boat ride to Butterfly Beach, honeymoners cave, and dolphin watching. Evening beachside seafood candle dinner.",
      },
      {
        day: 5,
        title: "Cabo de Rama Fort & Departure",
        description: "Visit the historic clifftop Cabo de Rama Fort overlooking turquoise seas. Enjoy breakfast and proceed for private transfer to airport/station.",
      },
    ],
    inclusions: [
      "4 Nights Premium Resort Stay in South Goa",
      "Daily Breakfast & Authentic Spice Plantation Lunch",
      "Old Goa & Fontainhas Heritage Entry Tickets",
      "Private AC Sedan for Full Duration",
      "All Tolls, Parking & Driver Allowances",
    ],
    detailedInclusions: [
      {
        id: "inc-2-1",
        title: "4 Nights Boutique Heritage Resort in South Goa",
        description: "Unwind in pristine South Goa surrounded by coconut groves and quiet beaches. Complete with swimming pool, landscaped gardens, and complimentary morning breakfast spreads.",
        image: "https://images.unsplash.com/photo-1587922546307-776227941871?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-2-2",
        title: "Guided Fontainhas Latin Quarter & Church Walk",
        description: "Explore the picturesque 18th-century Portuguese streets of Fontainhas, historic houses, art galleries, and UNESCO World Heritage churches with an experienced local guide.",
        image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-2-3",
        title: "Private Sanitized AC Sedan for the Entire Duration",
        description: "Clean, comfortable air-conditioned cab dedicated exclusively to your group for all airport transfers, heritage monument visits, and evening excursions.",
        image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-2-4",
        title: "Authentic Goan Spice Plantation Tour & Buffet Lunch",
        description: "Immerse yourself in fragrant vanilla, cardamom, and cinnamon plantations followed by a traditional Saraswat Goan lunch served fresh on banana leaves.",
        image: "",
      },
    ],
    exclusions: [
      "Flight/Train tickets",
      "Personal expenses & tipping",
      "Alcoholic beverages",
    ],
    featured: true,
  },
  {
    id: "pkg-goa-3",
    state: "Goa",
    title: "Complete Goa Explorer (North & South Combined)",
    subtitle: "Beaches, Nightlife, Heritage & Water Cruise",
    route: "3N North Goa • 2N South Goa",
    duration: "6 Days & 5 Nights",
    categoryBadge: "All-Inclusive Family Special",
    badgeGradient: "from-emerald-500 to-teal-500",
    image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=800&auto=format&fit=crop",
    originalPrice: "24,000",
    discountedPrice: "17,999",
    savings: "6,001",
    highlights: [
      "Calangute, Baga & Anjuna Flea Market",
      "Casino Cruise Experience in Panaji",
      "Palolem & Butterfly Beach Boat Tour",
      "Dudhsagar Fall Safari & Elephant Wash",
    ],
    itinerary: [
      {
        day: 1,
        title: "North Goa Arrival & Calangute Check-in",
        description: "Arrival at Goa airport. Private pickup and check-in to North Goa hotel. Evening free to explore the iconic Calangute nightlife and beach street food.",
      },
      {
        day: 2,
        title: "North Goa Forts & Watersport Hub",
        description: "Visit Fort Aguada, Chapora Fort, Vagator & Morjim beaches. Optional parasailing, banana ride, and jet ski at Baga beach.",
      },
      {
        day: 3,
        title: "Dudhsagar Waterfall Jeep Safari",
        description: "Full-day jungle expedition in Bhagwan Mahavir Wildlife Sanctuary with 4x4 open jeep safari to the base of Dudhsagar Waterfall. Enjoy freshwater swimming.",
      },
      {
        day: 4,
        title: "Old Goa Heritage & South Goa Hotel Switch",
        description: "Check out from North Goa. Visit Bom Jesus church and Mangueshi temple. Check in to South Goa resort. Evening Panaji floating casino experience.",
      },
      {
        day: 5,
        title: "South Goa Beaches & Coastal Leisure",
        description: "Relax at Colva and Benaulim beaches. Visit Big Foot Goan village museum and local fishing harbor.",
      },
      {
        day: 6,
        title: "Departure Transfer",
        description: "Breakfast at resort. Free morning for shopping in Margao. Private transfer to airport / railway station.",
      },
    ],
    inclusions: [
      "5 Nights Split Stay (3N North + 2N South)",
      "Daily Breakfast at both properties",
      "Dudhsagar Jeep Safari & Forest Permits",
      "All Sightseeing & Inter-Hotel Transfers by AC Cab",
      "24/7 Dedicated WhatsApp Support from Priykant Gupta",
    ],
    detailedInclusions: [
      {
        id: "inc-3-1",
        title: "5 Nights Split Stay (3N North Goa + 2N South Goa)",
        description: "Experience both worlds of Goa: the vibrant energy of North Goa beaches and the peaceful, pristine luxury of South Goa resorts.",
        image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-3-2",
        title: "4x4 Open Jeep Jungle Safari to Dudhsagar Waterfalls",
        description: "Thrilling off-road drive crossing jungle rivers in Bhagwan Mahavir Sanctuary to the foot of India's fifth tallest multi-tiered waterfall.",
        image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-3-3",
        title: "Private Dedicated Vehicle for Sightseeing & Hotel Shifting",
        description: "No hassle of booking multiple cabs. Our private AC vehicle stays with you for all beach visits, transfers, and luggage shifts.",
        image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-3-4",
        title: "All Tolls, Parking, Inter-State Permits & Driver Allowances",
        description: "100% transparent pricing with zero surprise charges. All driver food allowances, night charges, state entry taxes and parking are prepaid.",
        image: "",
      },
    ],
    exclusions: [
      "Casino entry chips",
      "Flight / train fares",
      "Watersports fee",
    ],
    featured: true,
  },
  {
    id: "pkg-goa-4",
    state: "Goa",
    title: "Goa Romantic Special (Honeymoon & Couples)",
    subtitle: "Candlelight Dinner & Private Yacht Cruise",
    route: "3N Private Beachfront Resort",
    duration: "4 Days & 3 Nights",
    categoryBadge: "Couple & Honeymoon",
    badgeGradient: "from-amber-500 to-rose-500",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop",
    originalPrice: "22,000",
    discountedPrice: "16,499",
    savings: "5,501",
    highlights: [
      "Decorated Sunset Candlelight Beach Dinner",
      "Private Yacht Cruise with Non-Alcoholic Wine",
      "Flower Bed Decoration & Couple Spa",
      "Candlelit Cabana Experience",
    ],
    itinerary: [
      {
        day: 1,
        title: "Romantic Welcome & Candlelight Dinner",
        description: "VIP airport pickup with flower bouquet. Check-in to decorated honeymoon suite with welcome cake. Evening private candlelight dinner setup on the beach with complimentary bottle of wine/mocktails.",
      },
      {
        day: 2,
        title: "Private Luxury Yacht Sailing & Sunset Point",
        description: "Private 2-hour luxury yacht charter sailing along Mandovi river into the Arabian Sea. Enjoy music, fruits, and sunset photography. Visit Sinquerim sunset viewpoint.",
      },
      {
        day: 3,
        title: "South Goa Scenic Drive & Rejuvenating Spa",
        description: "Leisure morning followed by a rejuvenating 60-minute couple Ayurvedic spa therapy at the resort. Evening leisurely drive to Dona Paula viewpoint and Miramar beach.",
      },
      {
        day: 4,
        title: "Sweet Goodbyes & Airport Drop",
        description: "Breakfast in bed. Check out and private cab transfer to airport with sweet memories of Goa.",
      },
    ],
    inclusions: [
      "3 Nights Luxury Beachfront Honeymoon Suite",
      "Daily Buffet Breakfast",
      "1 Candlelight Beach Dinner with Special Table Decor",
      "Special Honeymoon Cake & Bed Floral Arrangement",
      "Private 2-Hour Yacht / Luxury Boat Charter",
      "Exclusive AC Cab for Airport & Sightseeing Transfers",
    ],
    detailedInclusions: [
      {
        id: "inc-4-1",
        title: "Private Beachside Candlelight Dinner with Table Decor",
        description: "A private decorated table on the sand overlooking the Arabian waves, decorated with fairy lights, floral centerpieces, gourmet 4-course meal, and welcome drinks.",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-4-2",
        title: "2-Hour Private Catamaran Yacht Charter",
        description: "Sail into the sunset on a private luxury yacht with your own captain and crew. Includes soft beverages, tropical fruit platter, and romantic music on the waters.",
        image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-4-3",
        title: "Luxury Beachfront Honeymoon Suite with Floral Bed Decor",
        description: "Special honeymoon welcome with exotic flower bed arrangement, artisan chocolate cake, fruit basket, and daily breakfast served in bed.",
        image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "inc-4-4",
        title: "Exclusive Chauffeur-Driven AC Sedan for All Sightseeing",
        description: "Dedicated private vehicle with romantic sightseeing route, Dona Paula viewpoint, Chapora sunset cliff, and timely airport pickup and drop.",
        image: "",
      },
    ],
    exclusions: [
      "Airfare (can be booked via R Travel at partner discounts)",
      "Any extra activities outside itinerary",
    ],
    featured: true,
  },
];

