import { CompanyInfo, Destination, TravelService, CuratedPackage } from "./types";

export const companyData: CompanyInfo = {
  name: "WATCH MY TRIP PACKAGE",
  tagline: "Your Journey, Our Responsibility",
  founder: "Masrur Ahmed",
  director: "Masum Ahmed",
  experienceYears: "15+",
  satisfiedCustomers: "25,000+",
  formerName: "Ranjan Services",
  address: "Golden Beach Road, Calangute Beach, Calangute, Goa - 403516",
  phones: ["+91 95886 67027", "+91 70583 23165"],
  whatsapp: "919588667027",
  emails: ["info@rtravelworld.com", "rtravelworldmehsana@gmail.com"],
  instagram: "https://www.instagram.com/watchmytrippackage?stkn=MWxieXNncG5hcDl4OA%3D%3D&utm_source=qr",
};

export const goaCarouselSlides = [
  {
    id: "goa-summer-offer",
    title: "Hotel Small Daddy Plus Signature Package",
    subtitle: "4N/5D Summer Best Offer: Dinner Cruise, Adventure Boat Party, North/South Tour & Full Body Spa.",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=1600&auto=format&fit=crop",
    badge: "Summer Best Offer: ₹2,499 / Day",
    tag: "Summer Best Offer",
    price: "From ₹9,996 / person",
  },
  {
    id: "goa-2",
    title: "Heritage Forts & Portuguese Villas",
    subtitle: "Wander through colorful Latin quarters of Fontainhas, historic Aguada & Chapora Forts.",
    image: "https://images.unsplash.com/photo-1587922546307-776227941871?q=80&w=1600&auto=format&fit=crop",
    badge: "Cultural & Heritage Tours",
    tag: "Historical Marvels",
    price: "From ₹14,499 / person",
  },
  {
    id: "goa-3",
    title: "Luxury Catamaran & Island Cruises",
    subtitle: "Sail along the pristine Mandovi river, spot dolphins at Grand Island, and enjoy watersports.",
    image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?q=80&w=1600&auto=format&fit=crop",
    badge: "VIP Yacht & Watersport Experience",
    tag: "Adventure & Thrill",
    price: "From ₹16,999 / person",
  },
  {
    id: "goa-4",
    title: "Tropical Palms & Serene Backwaters",
    subtitle: "Unwind at tranquil South Goa resorts surrounded by emerald palms and serene coastal rivers.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600&auto=format&fit=crop",
    badge: "Custom Family & Honeymoon Retreat",
    tag: "Ultimate Relaxation",
    price: "From ₹18,500 / person",
  },
];

export const destinationsData: Destination[] = [
  {
    id: "gujarat",
    name: "Gujarat",
    tagline: "Land of Legends",
    category: "india",
    image: "https://images.unsplash.com/photo-1609137144813-7d9921338f24?q=80&w=800&auto=format&fit=crop",
    duration: "5 Days / 4 Nights",
    startingPrice: "₹14,999",
    featured: true,
    highlights: ["Rann of Kutch", "Statue of Unity", "Somnath & Dwarka Temple", "Gir National Park"],
  },
  {
    id: "kashmir",
    name: "Kashmir",
    tagline: "Paradise on Earth",
    category: "india",
    image: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹19,499",
    featured: true,
    highlights: ["Dal Lake Shikara", "Gulmarg Gondola", "Pahalgam Valley", "Sonamarg Glaciers"],
  },
  {
    id: "himachal",
    name: "Himachal Pradesh",
    tagline: "Snowy Peaks & Alpine Wonder",
    category: "india",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹16,999",
    featured: true,
    highlights: ["Manali & Rohtang Pass", "Shimla Ridge", "Solang Valley", "Kasol & Spiti"],
  },
  {
    id: "uttarakhand",
    name: "Uttarakhand",
    tagline: "Devbhoomi Valley & Serenity",
    category: "india",
    image: "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?q=80&w=800&auto=format&fit=crop",
    duration: "7 Days / 6 Nights",
    startingPrice: "₹18,500",
    featured: true,
    highlights: ["Rishikesh River Rafting", "Mussoorie Hills", "Nainital Lake", "Char Dham Yatra"],
  },
  {
    id: "goa",
    name: "Goa",
    tagline: "Sun, Sea & Golden Beaches",
    category: "india",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=800&auto=format&fit=crop",
    duration: "4 Days / 3 Nights",
    startingPrice: "₹12,999",
    featured: true,
    highlights: ["Baga Beach Nightlife", "Dudhsagar Waterfalls", "Scuba & Watersports", "Private Yacht Cruises"],
  },
  {
    id: "kerala",
    name: "Kerala",
    tagline: "God's Own Country",
    category: "india",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹17,999",
    featured: true,
    highlights: ["Alleppey Houseboat", "Munnar Tea Gardens", "Thekkady Wildlife", "Kovalam Beach"],
  },
  {
    id: "maharashtra",
    name: "Maharashtra",
    tagline: "Heritage & Mist-Covered Hills",
    category: "india",
    image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?q=80&w=800&auto=format&fit=crop",
    duration: "4 Days / 3 Nights",
    startingPrice: "₹11,999",
    featured: false,
    highlights: ["Mahabaleshwar & Lonavala", "Ajanta & Ellora Caves", "Alibaug Coast", "Shirdi Darshan"],
  },
  {
    id: "tamil-nadu",
    name: "Tamil Nadu",
    tagline: "Land of Ancient Temples",
    category: "india",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=800&auto=format&fit=crop",
    duration: "5 Days / 4 Nights",
    startingPrice: "₹15,499",
    featured: false,
    highlights: ["Madurai Meenakshi", "Rameshwaram Corridor", "Ooty Toy Train", "Kanyakumari Sunset"],
  },
  {
    id: "odisha",
    name: "Odisha",
    tagline: "Art, Heritage & Temples",
    category: "india",
    image: "https://images.unsplash.com/photo-1620619767323-b95a89183081?q=80&w=800&auto=format&fit=crop",
    duration: "5 Days / 4 Nights",
    startingPrice: "On Request",
    featured: false,
    highlights: ["Puri Jagannath Temple", "Konark Sun Temple", "Chilika Lake Dolphins", "Bhubaneswar Heritage"],
  },
  {
    id: "sikkim",
    name: "Sikkim",
    tagline: "Himalayan Beauty & Monasteries",
    category: "india",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹21,999",
    featured: true,
    highlights: ["Tsomgo Lake", "Nathula Pass", "Gangtok Cable Car", "Yumthang Flower Valley"],
  },
  {
    id: "darjeeling",
    name: "Darjeeling",
    tagline: "Queen of the Hills",
    category: "india",
    image: "https://images.unsplash.com/photo-1569154941061-e231b4725ef1?q=80&w=800&auto=format&fit=crop",
    duration: "4 Days / 3 Nights",
    startingPrice: "₹14,500",
    featured: false,
    highlights: ["Tiger Hill Sunrise", "Batasia Loop", "Toy Train Joy Ride", "Happy Valley Tea Estate"],
  },
  {
    id: "meghalaya",
    name: "Meghalaya",
    tagline: "Abode of Clouds & Living Roots",
    category: "india",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=800&auto=format&fit=crop",
    duration: "5 Days / 4 Nights",
    startingPrice: "₹19,999",
    featured: false,
    highlights: ["Cherrapunji Waterfalls", "Dawki Crystal River", "Living Root Bridges", "Mawlynnong Village"],
  },
  {
    id: "andaman",
    name: "Andaman & Nicobar",
    tagline: "Tropical Island Paradise",
    category: "india",
    image: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹24,999",
    featured: true,
    highlights: ["Radhanagar Beach Havelock", "Scuba & Coral Snorkeling", "Cellular Jail Light Show", "Neil Island"],
  },
  {
    id: "ladakh",
    name: "Leh Ladakh",
    tagline: "High Mountain Passes & Pangong Tso",
    category: "india",
    image: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?q=80&w=800&auto=format&fit=crop",
    duration: "7 Days / 6 Nights",
    startingPrice: "₹26,999",
    featured: true,
    highlights: ["Pangong Tso Blue Lake", "Khardung La World's Highest Pass", "Nubra Valley Sand Dunes", "Magnetic Hill"],
  },
  // International Destinations
  {
    id: "dubai",
    name: "Dubai, UAE",
    tagline: "Futuristic Wonder & Desert Safaris",
    category: "international",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=800&auto=format&fit=crop",
    duration: "5 Days / 4 Nights",
    startingPrice: "₹45,999",
    featured: true,
    highlights: ["Burj Khalifa Top Floor", "Desert Dune Bashing & BBQ", "Marina Dhow Cruise", "Museum of the Future"],
  },
  {
    id: "bali",
    name: "Bali, Indonesia",
    tagline: "Island of Gods & Tropical Luxury",
    category: "international",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹42,500",
    featured: true,
    highlights: ["Ubud Rice Terraces", "Tanah Lot Sea Temple", "Nusa Penida Kelingking", "Private Pool Villa Stay"],
  },
  {
    id: "maldives",
    name: "Maldives",
    tagline: "Overwater Villas & Turquoise Lagoons",
    category: "international",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=800&auto=format&fit=crop",
    duration: "4 Days / 3 Nights",
    startingPrice: "₹59,999",
    featured: true,
    highlights: ["Luxury Water Villa Stay", "Manta Ray Snorkeling", "Sunset Speedboat Cruise", "Candlelight Beach Dinner"],
  },
  {
    id: "thailand",
    name: "Thailand (Phuket & Krabi)",
    tagline: "Emerald Bays & Vibrant Culture",
    category: "international",
    image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=800&auto=format&fit=crop",
    duration: "6 Days / 5 Nights",
    startingPrice: "₹34,999",
    featured: true,
    highlights: ["Phi Phi Island Speedboat", "James Bond Island", "Bangkok Grand Palace", "Coral Reef Snorkeling"],
  },
  {
    id: "singapore",
    name: "Singapore",
    tagline: "Garden City & Universal Studios",
    category: "international",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=800&auto=format&fit=crop",
    duration: "5 Days / 4 Nights",
    startingPrice: "₹52,000",
    featured: false,
    highlights: ["Marina Bay Sands SkyPark", "Gardens by the Bay", "Sentosa Island", "Night Safari"],
  },
  {
    id: "switzerland",
    name: "Switzerland",
    tagline: "Alpine Enchantment & Scenic Trains",
    category: "international",
    image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=800&auto=format&fit=crop",
    duration: "7 Days / 6 Nights",
    startingPrice: "₹1,25,000",
    featured: true,
    highlights: ["Jungfraujoch Top of Europe", "Mount Titlis Cable Car", "Lake Lucerne Cruise", "Interlaken Valley"],
  },
];

export const servicesData: TravelService[] = [
  {
    id: "flight-booking",
    title: "Flight Booking",
    shortDesc: "Domestic & International airfares with exclusive agent fares and instant confirmation.",
    fullDesc: "Best rates for domestic and international carriers, special student & corporate baggage allowances, seat selection, and 24/7 web check-in assistance.",
    iconName: "Plane",
    badge: "Special Airfares",
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "railway-reservation",
    title: "Railway Reservation",
    shortDesc: "Hassle-free IRCTC confirmed bookings, Tatkal support & tourist train planning.",
    fullDesc: "Complete railway ticketing assistance across all classes (1AC, 2AC, 3AC, Vande Bharat, Tejas Express) with route guidance and meal selections.",
    iconName: "Train",
    badge: "Tatkal & Vande Bharat",
    image: "https://images.unsplash.com/photo-1532105956626-9569c03602f6?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "group-tours",
    title: "Group Tours",
    shortDesc: "Curated community & family group departures with dedicated tour managers.",
    fullDesc: "Stress-free group travel with inclusive meals, luxury AC coach transfers, Gujarati/Jain food arrangements, and expert local guides.",
    iconName: "Users",
    badge: "Guided Group Departures",
    image: "https://images.unsplash.com/photo-1539635278303-d4002c07eae3?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "corporate-tours",
    title: "Corporate Tours (MICE)",
    shortDesc: "Executive travel, annual retreats, dealer meets, and incentive conference trips.",
    fullDesc: "End-to-end MICE solutions including conference hall setups, team bonding adventures, airport meet & greets, and bulk billing.",
    iconName: "Briefcase",
    badge: "MICE & Business Travel",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "customized-holidays",
    title: "Customized Holidays",
    shortDesc: "Tailor-made itineraries designed exclusively to match your exact dates and budget.",
    fullDesc: "Choose your pace, select boutique stays, personalize daily sightseeing, and travel with your own private vehicle and chauffeur.",
    iconName: "Compass",
    badge: "100% Tailored Itinerary",
    image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "domestic-tour-packages",
    title: "Domestic Tour Packages",
    shortDesc: "Comprehensive holiday packages covering the vibrant states of India.",
    fullDesc: "From Kashmir to Kanyakumari, and Gujarat to the North East, experience verified 3-star to 5-star hotels, safe transport, and curated sightseeing.",
    iconName: "MapPin",
    badge: "All-India Coverage",
    image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "family-holidays",
    title: "Family Holidays",
    shortDesc: "Safe, comfortable vacations packed with fun for children and leisure for elders.",
    fullDesc: "Kid-friendly resorts, spacious inter-connecting rooms, comfortable vehicle pacing, and memorable activities for every generation.",
    iconName: "HeartHandshake",
    badge: "All Generations Welcome",
    image: "https://images.unsplash.com/photo-1511895426328-dc8714191300?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "honeymoon-tours",
    title: "Honeymoon Tours",
    shortDesc: "Romantic getaways with candlelit dinners, flower beds, and private pool villas.",
    fullDesc: "Special inclusions like beachfront dinners, honeymoon cakes, couple spa sessions, and idyllic destinations like Maldives, Bali, Kashmir & Kerala.",
    iconName: "Sparkles",
    badge: "Romantic Specials",
    image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "pilgrimage-tours",
    title: "Pilgrimage Tours",
    shortDesc: "Spiritual journeys to holy shrines with senior citizen care and darshan arrangements.",
    fullDesc: "Specialized tours for Char Dham, Vaishno Devi, Somnath-Dwarka, Jyotirlinga Darshan, Tirupati, Shirdi, and Ayodhya with dedicated assistance.",
    iconName: "Sun",
    badge: "Spiritual Yatra Care",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "hotel-booking",
    title: "Hotel Booking",
    shortDesc: "Handpicked premium hotels, heritage havelis, beachfront stays & luxury resorts.",
    fullDesc: "Verified quality, best negotiated corporate rates, complimentary breakfasts, early check-in assistance, and guaranteed room categories.",
    iconName: "Building2",
    badge: "Verified Stays",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "car-rental",
    title: "Car Rental",
    shortDesc: "Chauffeur-driven AC sedans, Innova Crysta, tempo travellers & luxury coaches.",
    fullDesc: "Reliable intercity transfers, airport pick & drop, local sightseeing cabs with courteous verified drivers and zero surge pricing.",
    iconName: "Car",
    badge: "Clean Fleet & Verified Drivers",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800&auto=format&fit=crop",
  },
];

export const curatedRegionsList = [
  "Gujarat",
  "Uttar Pradesh",
  "Uttarakhand",
  "Himachal",
  "Jammu Kashmir",
  "North East",
  "Bengal & Odisha",
  "Kerala",
  "Tamil Nadu",
  "Goa",
  "Maharashtra",
  "Karnataka",
];

export { initialCuratedPackages } from "./curatedPackagesData";
